import type { Category, News, Media } from '@/payload-types'
import { RequiredDataFromCollectionSlug } from 'payload'

type NewsArgs = {
  featuredImage: Media
  categories: Category[]
}

export const newsCompanyData: (args: NewsArgs) => RequiredDataFromCollectionSlug<'news'> = ({
  featuredImage,
  categories,
}) => {
  return {
    title: 'Vinatetco Kỷ Niệm 50 Năm Phát Triển',
    slug: 'vinatetco-ky-niem-50-nam-phat-trien',
    excerpt: 'Công ty Thuốc Thú Y TW1 (Vinatetco) tự hào kỷ niệm 50 năm cống hiến cho ngành dược thú y Việt Nam.',
    content: {
      root: {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Sau 50 năm hình thành và phát triển, Vinatetco đã trở thành thương hiệu uy tín hàng đầu trong lĩnh vực dược thú y tại Việt Nam. Với sứ mệnh cung cấp các giải pháp chăm sóc sức khỏe động vật toàn diện, chúng tôi đã đồng hành cùng hàng nghìn hộ nông dân và doanh nghiệp chăn nuôi trên khắp cả nước.',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Trong suốt 5 thập kỷ qua, Vinatetco đã đạt được nhiều thành tựu quan trọng:',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '• Xây dựng nhà máy sản xuất đạt chuẩn GMP-WHO',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '• Phát triển hơn 200 loại sản phẩm dược thú y',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '• Xuất khẩu sản phẩm sang hơn 30 quốc gia',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'root',
        version: 1,
      },
    },
    featuredImage: featuredImage.id,
    category: 'company',
    publishedDate: '2025-11-01T00:00:00.000Z',
    featured: true,
  }
}

export const newsIndustryData: (args: NewsArgs) => RequiredDataFromCollectionSlug<'news'> = ({
  featuredImage,
  categories,
}) => {
  return {
    title: 'Xu Hướng Nuôi Trồng Thủy Sản Bền Vững Tại Việt Nam',
    slug: 'xu-huong-nuoi-trong-thuy-san-ben-vung-tai-viet-nam',
    excerpt: 'Ngành nuôi trồng thủy sản Việt Nam đang chuyển hướng sang các mô hình bền vững, thân thiện với môi trường.',
    content: {
      root: {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Ngành nuôi trồng thủy sản Việt Nam đang chứng kiến sự chuyển biến mạnh mẽ hướng tới các mô hình sản xuất bền vững. Theo số liệu từ Bộ Nông nghiệp và Phát triển nông thôn, sản lượng thủy sản năm 2024 đạt hơn 9 triệu tấn, tăng 2.5% so với năm trước.',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Các xu hướng chính trong ngành bao gồm:',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '• Áp dụng công nghệ nuôi trồng thủy sản tuần hoàn (RAS)',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '• Sử dụng thức ăn thủy sản hữu cơ, thân thiện môi trường',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '• Triển khai hệ thống quản lý chất lượng nghiêm ngặt',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'root',
        version: 1,
      },
    },
    featuredImage: featuredImage.id,
    category: 'industry',
    publishedDate: '2025-10-28T00:00:00.000Z',
    featured: false,
  }
}

export const newsVaccineData: (args: NewsArgs) => RequiredDataFromCollectionSlug<'news'> = ({
  featuredImage,
  categories,
}) => {
  return {
    title: 'Công Nghệ Vaccine Mới Phòng Bệnh Cho Gia Súc',
    slug: 'cong-nghe-vaccine-moi-phong-benh-cho-gia-suc',
    excerpt: 'Vinatetco giới thiệu công nghệ vaccine thế hệ mới với hiệu quả bảo vệ cao hơn 95%.',
    content: {
      root: {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Vinatetco vừa chính thức giới thiệu dòng vaccine thế hệ mới sử dụng công nghệ protein tái tổ hợp. Các sản phẩm này mang lại hiệu quả bảo vệ lên tới 95% đối với các bệnh truyền nhiễm phổ biến ở gia súc.',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Ưu điểm nổi bật của công nghệ mới:',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '• An toàn tuyệt đối, không gây phản ứng phụ',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '• Thời gian bảo vệ kéo dài 12-18 tháng',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '• Chi phí sản xuất thấp, dễ tiếp cận với nông dân',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'root',
        version: 1,
      },
    },
    featuredImage: featuredImage.id,
    category: 'company',
    publishedDate: '2025-10-25T00:00:00.000Z',
    featured: true,
  }
}

export const newsOrganicData: (args: NewsArgs) => RequiredDataFromCollectionSlug<'news'> = ({
  featuredImage,
  categories,
}) => {
  return {
    title: 'Vinatetco Ra Mắt Dòng Sản Phẩm Thú Y Hữu Cơ',
    slug: 'vinatetco-ra-mat-dong-san-pham-thu-y-huu-co',
    excerpt: 'Dòng sản phẩm thú y hữu cơ mới từ Vinatetco đáp ứng nhu cầu chăn nuôi bền vững, thân thiện môi trường.',
    content: {
      root: {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Vinatetco chính thức ra mắt dòng sản phẩm thú y hữu cơ đầu tiên tại Việt Nam, đánh dấu bước ngoặt quan trọng trong việc chuyển đổi sang mô hình chăn nuôi bền vững. Các sản phẩm được chiết xuất 100% từ nguyên liệu tự nhiên, không chứa hóa chất độc hại.',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Dòng sản phẩm bao gồm:',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '• Thuốc bổ gan thận từ thảo dược tự nhiên',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '• Kháng sinh tự nhiên từ tỏi và gừng',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '• Vitamin tổng hợp từ rau củ quả organic',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'root',
        version: 1,
      },
    },
    featuredImage: featuredImage.id,
    category: 'company',
    publishedDate: '2025-10-20T00:00:00.000Z',
    featured: false,
  }
}

export const newsPartnershipData: (args: NewsArgs) => RequiredDataFromCollectionSlug<'news'> = ({
  featuredImage,
  categories,
}) => {
  return {
    title: 'Vinatetco Hợp Tác Với Hiệp Hội Chăn Nuôi Việt Nam',
    slug: 'vinatetco-hop-tac-voi-hiep-hoi-chan-nuoi-viet-nam',
    excerpt: 'Chương trình hợp tác chiến lược giữa Vinatetco và HAVETCO hướng tới phát triển ngành chăn nuôi bền vững.',
    content: {
      root: {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Vinatetco và Hiệp hội Chăn nuôi Việt Nam (HAVETCO) chính thức ký kết thỏa thuận hợp tác chiến lược nhằm nâng cao chất lượng ngành chăn nuôi trong nước. Chương trình hợp tác kéo dài 5 năm với tổng kinh phí đầu tư 50 tỷ đồng.',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Các nội dung hợp tác chính:',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '• Nghiên cứu và phát triển giống vật nuôi mới',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '• Đào tạo kỹ thuật viên chăn nuôi chuyên nghiệp',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '• Tư vấn kỹ thuật và chuyển giao công nghệ',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'root',
        version: 1,
      },
    },
    featuredImage: featuredImage.id,
    category: 'company',
    publishedDate: '2025-10-15T00:00:00.000Z',
    featured: true,
  }
}

export const newsExportData: (args: NewsArgs) => RequiredDataFromCollectionSlug<'news'> = ({
  featuredImage,
  categories,
}) => {
  return {
    title: 'Vinatetco Xuất Khẩu Thành Công Sang Thị Trường Châu Âu',
    slug: 'vinatetco-xuat-khau-thanh-cong-sang-thi-truong-chau-au',
    excerpt: 'Lần đầu tiên sản phẩm thú y Việt Nam được xuất khẩu chính ngạch sang thị trường EU, mở ra cơ hội mới cho ngành dược thú y nội địa.',
    content: {
      root: {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Sau 2 năm đàm phán và đáp ứng đầy đủ các tiêu chuẩn nghiêm ngặt của Liên minh Châu Âu, Vinatetco chính thức xuất khẩu lô vaccine phòng bệnh cho gia súc đầu tiên sang thị trường EU. Đây là thành công đầu tiên của doanh nghiệp dược thú y Việt Nam trên thị trường xuất khẩu khó tính nhất thế giới.',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Các yếu tố then chốt dẫn đến thành công:',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '• Đạt chứng nhận GMP-WHO quốc tế',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '• Công nghệ sản xuất đạt chuẩn EU-GMP',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '• Hệ thống quản lý chất lượng toàn diện',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'root',
        version: 1,
      },
    },
    featuredImage: featuredImage.id,
    category: 'company',
    publishedDate: '2025-10-10T00:00:00.000Z',
    featured: true,
  }
}

export const newsIndustryLivestockData: (args: NewsArgs) => RequiredDataFromCollectionSlug<'news'> = ({
  featuredImage,
  categories,
}) => {
  return {
    title: 'Ngành Chăn Nuôi Gia Súc Việt Nam 2025: Cơ Hội Và Thách Thức',
    slug: 'nganh-chan-nuoi-gia-suc-viet-nam-2025-co-hoi-va-thach-thuc',
    excerpt: 'Ngành chăn nuôi gia súc Việt Nam đang đối mặt với nhiều cơ hội phát triển nhưng cũng phải giải quyết các thách thức về môi trường và an toàn thực phẩm.',
    content: {
      root: {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Theo báo cáo của Bộ Nông nghiệp và Phát triển nông thôn, ngành chăn nuôi gia súc Việt Nam năm 2025 đạt sản lượng 5.2 triệu tấn thịt các loại, tăng 8% so với năm trước. Tuy nhiên, ngành cũng đối mặt với nhiều thách thức về ô nhiễm môi trường và an toàn thực phẩm.',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Các xu hướng phát triển chính:',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '• Chuyển đổi sang chăn nuôi công nghệ cao',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '• Áp dụng quản lý chất lượng nghiêm ngặt',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '• Phát triển chăn nuôi hữu cơ và bền vững',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'root',
        version: 1,
      },
    },
    featuredImage: featuredImage.id,
    category: 'industry',
    publishedDate: '2025-10-05T00:00:00.000Z',
    featured: false,
  }
}
